version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - arguments-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  arguments-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arguments-backend
    ports:
      - "24833:24833"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/arguments
      - SPRING_DATA_MONGODB_DATABASE=arguments
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - arguments-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - arguments-network

networks:
  arguments-network:
    driver: bridge

volumes:
  mongodb_data:
  ollama_data: