package com.asier.arguments.misc

enum class StatusCodes {
    UNAUTHORIZED_CLIENT, SUCCESSFULLY, INVALID_CREDENTIALS, UNKNOWN, NOT_FOUND, UNAUTHORIZED_AUTH, EXPIRED_DISCUSSION, DISCUSSION_MAX_REACHED, NOT_A_MEMBER, USER_ALREADY_VOTED, VOTING_CLOSED

}